[project]
name = "lkio"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "orjson>=3.12.0",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "sqlalchemy>=2.0.54",
    "tree-sitter==0.25.2",
    "tree-sitter-java==0.23.5",
    "tree-sitter-javascript==0.25.0",
    "tree-sitter-typescript==0.23.2",
    "typer>=0.27.2",
]
