"""100 Query Gold Set Definition for LKIO MVP3 RAG Acceptance Gate.
Covers 6 categories across HELLO_FE, HELLO_BE, and L2C_FE projects.
"""

GOLD_SET_100 = [
    # ---------------------------------------------------------
    # Category 1: ENTITY_LOCALIZATION (20 Queries)
    # ---------------------------------------------------------
    {
        "id": "Q001",
        "category": "ENTITY_LOCALIZATION",
        "query": "NorthAmericaSalesDailyReportRowDTO 在哪里？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyReportRowDTO", "NorthAmericaSalesDailyReportRowDTO.java"],
    },
    {
        "id": "Q002",
        "category": "ENTITY_LOCALIZATION",
        "query": "NorthAmericaSalesDailyDetailMetricsService 定义在哪个文件？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyDetailMetricsService", "NorthAmericaSalesDailyDetailMetricsService.java"],
    },
    {
        "id": "Q003",
        "category": "ENTITY_LOCALIZATION",
        "query": "NorthAmericaSalesDailyReportServiceImpl 类的完整路径是什么？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyReportServiceImpl", "NorthAmericaSalesDailyReportServiceImpl.java"],
    },
    {
        "id": "Q004",
        "category": "ENTITY_LOCALIZATION",
        "query": "LeadConversionService 实体位置",
        "project": "HELLO_BE",
        "expected_matches": ["LeadConversionService", "leadconversion"],
    },
    {
        "id": "Q005",
        "category": "ENTITY_LOCALIZATION",
        "query": "TelemarketingCallService 接口定义在哪里？",
        "project": "HELLO_BE",
        "expected_matches": ["TelemarketingCallService", "telemarketing"],
    },
    {
        "id": "Q006",
        "category": "ENTITY_LOCALIZATION",
        "query": "L2C 前端中 auth.ts 文件在哪里？",
        "project": "L2C_FE",
        "expected_matches": ["auth.ts", "apps/web-ele/src/api/core/auth.ts"],
    },
    {
        "id": "Q007",
        "category": "ENTITY_LOCALIZATION",
        "query": "L2C 菜单接口 menu.ts 定义在哪个目录？",
        "project": "L2C_FE",
        "expected_matches": ["menu.ts", "apps/web-ele/src/api/core/menu.ts"],
    },
    {
        "id": "Q008",
        "category": "ENTITY_LOCALIZATION",
        "query": "user.ts 用户 API 模块位置",
        "project": "L2C_FE",
        "expected_matches": ["user.ts", "apps/web-ele/src/api/core/user.ts"],
    },
    {
        "id": "Q009",
        "category": "ENTITY_LOCALIZATION",
        "query": "request.ts 网络请求封装在哪里？",
        "project": "L2C_FE",
        "expected_matches": ["request.ts", "apps/web-ele/src/api/request.ts"],
    },
    {
        "id": "Q010",
        "category": "ENTITY_LOCALIZATION",
        "query": "L2C 布局组件 basic.vue 放在哪里？",
        "project": "L2C_FE",
        "expected_matches": ["basic.vue", "apps/web-ele/src/layouts/basic.vue"],
    },
    {
        "id": "Q011",
        "category": "ENTITY_LOCALIZATION",
        "query": "登录页面 login.vue 的位置",
        "project": "L2C_FE",
        "expected_matches": ["login.vue", "authentication/login.vue"],
    },
    {
        "id": "Q012",
        "category": "ENTITY_LOCALIZATION",
        "query": "仪表盘分析页 analytics/index.vue 路径",
        "project": "L2C_FE",
        "expected_matches": ["analytics/index.vue", "dashboard/analytics/index.vue"],
    },
    {
        "id": "Q013",
        "category": "ENTITY_LOCALIZATION",
        "query": "工作台页面 workspace/index.vue 在哪里？",
        "project": "L2C_FE",
        "expected_matches": ["workspace/index.vue", "dashboard/workspace/index.vue"],
    },
    {
        "id": "Q014",
        "category": "ENTITY_LOCALIZATION",
        "query": "L2C 用户认证 store 是哪个文件？",
        "project": "L2C_FE",
        "expected_matches": ["store/auth.ts", "auth.ts"],
    },
    {
        "id": "Q015",
        "category": "ENTITY_LOCALIZATION",
        "query": "路由守卫 guard.ts 定义位置",
        "project": "L2C_FE",
        "expected_matches": ["router/guard.ts", "guard.ts"],
    },
    {
        "id": "Q016",
        "category": "ENTITY_LOCALIZATION",
        "query": "HELLO 前端中的 api/order.ts 在哪里？",
        "project": "HELLO_FE",
        "expected_matches": ["order.ts", "api/order.ts"],
    },
    {
        "id": "Q017",
        "category": "ENTITY_LOCALIZATION",
        "query": "HELLO 前端中的 requestClient 在哪里定义？",
        "project": "HELLO_FE",
        "expected_matches": ["requestClient", "request.ts"],
    },
    {
        "id": "Q018",
        "category": "ENTITY_LOCALIZATION",
        "query": "HELLO 后端的 SalesReportController 实体位置",
        "project": "HELLO_BE",
        "expected_matches": ["SalesReportController", "SalesReportController.java"],
    },
    {
        "id": "Q019",
        "category": "ENTITY_LOCALIZATION",
        "query": "L2C 共享常数 vben.ts 在哪个包里？",
        "project": "L2C_FE",
        "expected_matches": ["vben.ts", "packages/@core/base/shared/src/constants/vben.ts"],
    },
    {
        "id": "Q020",
        "category": "ENTITY_LOCALIZATION",
        "query": "L2C Echarts 插件 types.ts 定义在何处？",
        "project": "L2C_FE",
        "expected_matches": ["types.ts", "packages/effects/plugins/src/echarts/types.ts"],
    },

    # ---------------------------------------------------------
    # Category 2: CODE_LOCALIZATION (20 Queries)
    # ---------------------------------------------------------
    {
        "id": "Q021",
        "category": "CODE_LOCALIZATION",
        "query": "查找北美销售日报明细指标计算的核心实现代码",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyDetailMetricsService", "NorthAmericaSalesDailyDetailMetricsService.java"],
    },
    {
        "id": "Q022",
        "category": "CODE_LOCALIZATION",
        "query": "销售日报表聚合统计实现逻辑在哪里？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyReportServiceImpl", "NorthAmericaSalesDailyReportServiceImpl.java"],
    },
    {
        "id": "Q023",
        "category": "CODE_LOCALIZATION",
        "query": "电销外呼记录 CSV 数据读取与解析逻辑代码",
        "project": "HELLO_BE",
        "expected_matches": ["call-log", "telemarketing", "call-reports"],
    },
    {
        "id": "Q024",
        "category": "CODE_LOCALIZATION",
        "query": "L2C 用户登录与 Token 保存的实现代码",
        "project": "L2C_FE",
        "expected_matches": ["auth.ts", "login"],
    },
    {
        "id": "Q025",
        "category": "CODE_LOCALIZATION",
        "query": "L2C 菜单路由生成与权限过滤的实现逻辑",
        "project": "L2C_FE",
        "expected_matches": ["menu.ts", "guard.ts"],
    },
    {
        "id": "Q026",
        "category": "CODE_LOCALIZATION",
        "query": "Axios 请求拦截器中添加 Authorization Header 的代码",
        "project": "L2C_FE",
        "expected_matches": ["request.ts", "Authorization"],
    },
    {
        "id": "Q027",
        "category": "CODE_LOCALIZATION",
        "query": "Pinia auth store 中的 setToken 和 logout 方法实现",
        "project": "L2C_FE",
        "expected_matches": ["store/auth.ts", "auth.ts"],
    },
    {
        "id": "Q028",
        "category": "CODE_LOCALIZATION",
        "query": "Element Plus 表格和表单 Demo 页面代码在哪？",
        "project": "L2C_FE",
        "expected_matches": ["demos/element", "table", "form"],
    },
    {
        "id": "Q029",
        "category": "CODE_LOCALIZATION",
        "query": "分析大屏图表初始化与 Echarts 渲染逻辑代码",
        "project": "L2C_FE",
        "expected_matches": ["analytics", "echarts"],
    },
    {
        "id": "Q030",
        "category": "CODE_LOCALIZATION",
        "query": "工作台快捷入口与卡片布局组件代码",
        "project": "L2C_FE",
        "expected_matches": ["workspace/index.vue", "workspace"],
    },
    {
        "id": "Q031",
        "category": "CODE_LOCALIZATION",
        "query": "查找关于页面 about/index.vue 的信息展示代码",
        "project": "L2C_FE",
        "expected_matches": ["about/index.vue", "about"],
    },
    {
        "id": "Q032",
        "category": "CODE_LOCALIZATION",
        "query": "L2C 偏好设置 preferences 的读取和存储代码",
        "project": "L2C_FE",
        "expected_matches": ["preferences.ts", "preferences"],
    },
    {
        "id": "Q033",
        "category": "CODE_LOCALIZATION",
        "query": "多语言国际化 zh-CN 页面配置代码位置",
        "project": "L2C_FE",
        "expected_matches": ["zh-CN/page.json", "zh-CN/l2c.json"],
    },
    {
        "id": "Q034",
        "category": "CODE_LOCALIZATION",
        "query": "多语言国际化 en-US 页面配置代码位置",
        "project": "L2C_FE",
        "expected_matches": ["en-US/page.json", "en-US/l2c.json"],
    },
    {
        "id": "Q035",
        "category": "CODE_LOCALIZATION",
        "query": "Mock 数据生成代码在哪个文件？",
        "project": "L2C_FE",
        "expected_matches": ["mock-data.ts", "mock"],
    },
    {
        "id": "Q036",
        "category": "CODE_LOCALIZATION",
        "query": "HELLO 前端中用户订单列表渲染实现代码",
        "project": "HELLO_FE",
        "expected_matches": ["Order", "order.ts"],
    },
    {
        "id": "Q037",
        "category": "CODE_LOCALIZATION",
        "query": "HELLO 后端销售日报单元测试代码位置",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyDetailMetricsServiceTest.java", "Test"],
    },
    {
        "id": "Q038",
        "category": "CODE_LOCALIZATION",
        "query": "L2C 前端 Docker 构建与 Nginx 配置代码",
        "project": "L2C_FE",
        "expected_matches": ["Dockerfile", "docker-compose.yml"],
    },
    {
        "id": "Q039",
        "category": "CODE_LOCALIZATION",
        "query": "GitHub Actions 自动构建与镜像推送脚本",
        "project": "L2C_FE",
        "expected_matches": ["docker-build-push.yml", ".github/workflows"],
    },
    {
        "id": "Q040",
        "category": "CODE_LOCALIZATION",
        "query": "L2C 营销系统驾驶舱 cockpit 视图实现代码",
        "project": "L2C_FE",
        "expected_matches": ["cockpit", "marketing"],
    },

    # ---------------------------------------------------------
    # Category 3: RELATION_QUERY (20 Queries)
    # ---------------------------------------------------------
    {
        "id": "Q041",
        "category": "RELATION_QUERY",
        "query": "哪些类实现了 NorthAmericaSalesDailyReportService 接口？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyReportServiceImpl", "NorthAmericaSalesDailyReportServiceImpl.java"],
    },
    {
        "id": "Q042",
        "category": "RELATION_QUERY",
        "query": "NorthAmericaSalesDailyReportServiceImpl 调用了哪些下游服务？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyDetailMetricsService", "DetailMetrics"],
    },
    {
        "id": "Q043",
        "category": "RELATION_QUERY",
        "query": "哪些页面调用了 /api/auth/login 接口？",
        "project": "L2C_FE",
        "expected_matches": ["login.vue", "auth.ts", "/api/auth/login"],
    },
    {
        "id": "Q044",
        "category": "RELATION_QUERY",
        "query": "接口 /api/menu 由哪个前端模块发起调用？",
        "project": "L2C_FE",
        "expected_matches": ["menu.ts", "apps/web-ele/src/api/core/menu.ts"],
    },
    {
        "id": "Q045",
        "category": "RELATION_QUERY",
        "query": "路由守卫 guard.ts 引用了哪些 store 状态？",
        "project": "L2C_FE",
        "expected_matches": ["auth.ts", "store/auth.ts"],
    },
    {
        "id": "Q046",
        "category": "RELATION_QUERY",
        "query": "basic.vue 引用了哪些布局组件和偏好设置？",
        "project": "L2C_FE",
        "expected_matches": ["preferences.ts", "preferences"],
    },
    {
        "id": "Q047",
        "category": "RELATION_QUERY",
        "query": "哪些文件 import 了 @core/base/shared 中的常量？",
        "project": "L2C_FE",
        "expected_matches": ["vben.ts", "shared"],
    },
    {
        "id": "Q048",
        "category": "RELATION_QUERY",
        "query": "NorthAmericaSalesDailyDetailMetricsServiceTest 测试了哪个类？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyDetailMetricsService", "NorthAmericaSalesDailyDetailMetricsService.java"],
    },
    {
        "id": "Q049",
        "category": "RELATION_QUERY",
        "query": "哪个 Controller 提供了 /api/sales/daily 接口？",
        "project": "HELLO_BE",
        "expected_matches": ["SalesReportController", "NorthAmericaSalesDailyReportServiceImpl"],
    },
    {
        "id": "Q050",
        "category": "RELATION_QUERY",
        "query": "哪些文件使用了 Echarts 插件？",
        "project": "L2C_FE",
        "expected_matches": ["echarts.ts", "analytics/index.vue"],
    },
    {
        "id": "Q051",
        "category": "RELATION_QUERY",
        "query": "L2C 中 dashboard.ts 路由模块导出了哪些路由？",
        "project": "L2C_FE",
        "expected_matches": ["dashboard.ts", "analytics", "workspace"],
    },
    {
        "id": "Q052",
        "category": "RELATION_QUERY",
        "query": "demos.ts 路由模块引用了哪些 demo 页面？",
        "project": "L2C_FE",
        "expected_matches": ["demos.ts", "demos/element"],
    },
    {
        "id": "Q053",
        "category": "RELATION_QUERY",
        "query": "哪些页面引入了 Element Plus 的 Button 组件？",
        "project": "L2C_FE",
        "expected_matches": ["button.vue", "demos/element"],
    },
    {
        "id": "Q054",
        "category": "RELATION_QUERY",
        "query": "marketing.ts 路由指向哪些营销页面？",
        "project": "L2C_FE",
        "expected_matches": ["marketing.ts", "marketing"],
    },
    {
        "id": "Q055",
        "category": "RELATION_QUERY",
        "query": "sales.ts 路由包含哪些销售模块视图？",
        "project": "L2C_FE",
        "expected_matches": ["sales.ts", "sales"],
    },
    {
        "id": "Q056",
        "category": "RELATION_QUERY",
        "query": "system.ts 路由配置了哪些系统管理页面？",
        "project": "L2C_FE",
        "expected_matches": ["system.ts", "system"],
    },
    {
        "id": "Q057",
        "category": "RELATION_QUERY",
        "query": "HELLO 前端中哪些页面调用了 /api/orders 接口？",
        "project": "HELLO_FE",
        "expected_matches": ["order.ts", "/api/orders"],
    },
    {
        "id": "Q058",
        "category": "RELATION_QUERY",
        "query": "哪些类依赖了 NorthAmericaSalesDailyReportRowDTO？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyReportServiceImpl", "NorthAmericaSalesDailyDetailMetricsService"],
    },
    {
        "id": "Q059",
        "category": "RELATION_QUERY",
        "query": "谁调用了 auth.ts 中的 getAccessCodesApi？",
        "project": "L2C_FE",
        "expected_matches": ["guard.ts", "auth.ts"],
    },
    {
        "id": "Q060",
        "category": "RELATION_QUERY",
        "query": "requestClient 实例被哪些 API 模块引用？",
        "project": "L2C_FE",
        "expected_matches": ["auth.ts", "menu.ts", "user.ts"],
    },

    # ---------------------------------------------------------
    # Category 4: BUSINESS_EXPLANATION (15 Queries)
    # ---------------------------------------------------------
    {
        "id": "Q061",
        "category": "BUSINESS_EXPLANATION",
        "query": "北美销售日报表的指标统计口径与业务规则是什么？",
        "project": "HELLO_BE",
        "expected_matches": ["01-north-america-sales-daily-report.md", "NorthAmericaSalesDaily"],
    },
    {
        "id": "Q062",
        "category": "BUSINESS_EXPLANATION",
        "query": "电销外呼系统的通话时长与接通率如何统计？",
        "project": "HELLO_BE",
        "expected_matches": ["07-telemarketing-call-reports.md", "telemarketing"],
    },
    {
        "id": "Q063",
        "category": "BUSINESS_EXPLANATION",
        "query": "销售线索分配中地理位置与配额的业务设计",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSales", "lead"],
    },
    {
        "id": "Q064",
        "category": "BUSINESS_EXPLANATION",
        "query": "L2C 营销与销售全链路白皮书业务目标",
        "project": "L2C_FE",
        "expected_matches": ["L2C_FRONTEND_WHITEPAPER.md", "L2C"],
    },
    {
        "id": "Q065",
        "category": "BUSINESS_EXPLANATION",
        "query": "L2C 营销规范与业务全流程说明",
        "project": "L2C_FE",
        "expected_matches": ["MARKETING_L2C_SPEC.md", "marketing"],
    },
    {
        "id": "Q066",
        "category": "BUSINESS_EXPLANATION",
        "query": "商机阶段流转与转化率漏斗的定义",
        "project": "L2C_FE",
        "expected_matches": ["L2C_FRONTEND_WHITEPAPER.md", "sales"],
    },
    {
        "id": "Q067",
        "category": "BUSINESS_EXPLANATION",
        "query": "电销外呼测试报告中的主要发现和指标",
        "project": "HELLO_BE",
        "expected_matches": ["07-telemarketing-call-reports.md", "telemarketing"],
    },
    {
        "id": "Q068",
        "category": "BUSINESS_EXPLANATION",
        "query": "L2C 业务架构中的主干基线 MASTER_ARCHITECTURE_BASELINE",
        "project": "L2C_FE",
        "expected_matches": ["MASTER_ARCHITECTURE_BASELINE.md", "baseline"],
    },
    {
        "id": "Q069",
        "category": "BUSINESS_EXPLANATION",
        "query": "销售日报明细中每位销售人员的线索响应时间要求",
        "project": "HELLO_BE",
        "expected_matches": ["01-north-america-sales-daily-report.md", "SalesDaily"],
    },
    {
        "id": "Q070",
        "category": "BUSINESS_EXPLANATION",
        "query": "自研外呼系统的录音存储与质检业务规范",
        "project": "HELLO_BE",
        "expected_matches": ["07-telemarketing-call-reports.md", "telemarketing"],
    },
    {
        "id": "Q071",
        "category": "BUSINESS_EXPLANATION",
        "query": "L2C 驾驶舱中核心 KPI 的业务计算口径",
        "project": "L2C_FE",
        "expected_matches": ["cockpit", "L2C_FRONTEND_WHITEPAPER.md"],
    },
    {
        "id": "Q072",
        "category": "BUSINESS_EXPLANATION",
        "query": "线索状态流转从 New 到 Qualified 的条件",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSales", "lead"],
    },
    {
        "id": "Q073",
        "category": "BUSINESS_EXPLANATION",
        "query": "HELLO 后端报表体系的目录结构规划说明",
        "project": "HELLO_BE",
        "expected_matches": ["00-README.md", "docs/reports"],
    },
    {
        "id": "Q074",
        "category": "BUSINESS_EXPLANATION",
        "query": "项目关于未决问题与技术债务的记录 OPEN_QUESTIONS",
        "project": "L2C_FE",
        "expected_matches": ["OPEN_QUESTIONS.md", "PROJECT_FULL_SUMMARY.md"],
    },
    {
        "id": "Q075",
        "category": "BUSINESS_EXPLANATION",
        "query": "项目整体总结文档 PROJECT_FULL_SUMMARY",
        "project": "L2C_FE",
        "expected_matches": ["PROJECT_FULL_SUMMARY.md", "summary"],
    },

    # ---------------------------------------------------------
    # Category 5: HISTORY_QUERY (15 Queries)
    # ---------------------------------------------------------
    {
        "id": "Q076",
        "category": "HISTORY_QUERY",
        "query": "谁最近修改了 NorthAmericaSalesDailyReportServiceImpl.java？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyReportServiceImpl.java", "commit"],
    },
    {
        "id": "Q077",
        "category": "HISTORY_QUERY",
        "query": "NorthAmericaSalesDailyDetailMetricsService.java 的最近一次 commit 是什么？",
        "project": "HELLO_BE",
        "expected_matches": ["NorthAmericaSalesDailyDetailMetricsService.java", "commit"],
    },
    {
        "id": "Q078",
        "category": "HISTORY_QUERY",
        "query": "最近关于销售日报表修复的提交历史记录",
        "project": "HELLO_BE",
        "expected_matches": ["report", "sales", "commit"],
    },
    {
        "id": "Q079",
        "category": "HISTORY_QUERY",
        "query": "谁修改了 01-north-america-sales-daily-report.md 文档？",
        "project": "HELLO_BE",
        "expected_matches": ["01-north-america-sales-daily-report.md", "commit"],
    },
    {
        "id": "Q079b",
        "category": "HISTORY_QUERY",
        "query": "电销外呼报告 07-telemarketing-call-reports.md 的作者和提交时间",
        "project": "HELLO_BE",
        "expected_matches": ["07-telemarketing-call-reports.md", "commit"],
    },
    {
        "id": "Q080",
        "category": "HISTORY_QUERY",
        "query": "L2C 中 Dockerfile 最近是谁修改的？",
        "project": "L2C_FE",
        "expected_matches": ["Dockerfile", "commit"],
    },
    {
        "id": "Q081",
        "category": "HISTORY_QUERY",
        "query": "docker-build-push.yml 工作流的提交历史",
        "project": "L2C_FE",
        "expected_matches": ["docker-build-push.yml", "commit"],
    },
    {
        "id": "Q082",
        "category": "HISTORY_QUERY",
        "query": "谁提交了 L2C 前端白皮书 L2C_FRONTEND_WHITEPAPER.md？",
        "project": "L2C_FE",
        "expected_matches": ["L2C_FRONTEND_WHITEPAPER.md", "commit"],
    },
    {
        "id": "Q083",
        "category": "HISTORY_QUERY",
        "query": "关于 Element Plus demo 页面的最近修改记录",
        "project": "L2C_FE",
        "expected_matches": ["demos/element", "commit"],
    },
    {
        "id": "Q084",
        "category": "HISTORY_QUERY",
        "query": "谁修改了 apps/web-ele/src/api/core/auth.ts？",
        "project": "L2C_FE",
        "expected_matches": ["auth.ts", "commit"],
    },
    {
        "id": "Q085",
        "category": "HISTORY_QUERY",
        "query": "谁修改了 apps/web-ele/src/api/request.ts？",
        "project": "L2C_FE",
        "expected_matches": ["request.ts", "commit"],
    },
    {
        "id": "Q086",
        "category": "HISTORY_QUERY",
        "query": "L2C 路由守卫 guard.ts 的提交日志",
        "project": "L2C_FE",
        "expected_matches": ["guard.ts", "commit"],
    },
    {
        "id": "Q087",
        "category": "HISTORY_QUERY",
        "query": "谁在 HELLO 前端中修改了 mcp.json？",
        "project": "HELLO_FE",
        "expected_matches": ["mcp.json", "commit"],
    },
    {
        "id": "Q088",
        "category": "HISTORY_QUERY",
        "query": "HELLO 前端最近的提交记录是什么？",
        "project": "HELLO_FE",
        "expected_matches": ["commit", "HELLO_FE"],
    },
    {
        "id": "Q089",
        "category": "HISTORY_QUERY",
        "query": "最近针对 L2C 国际化配置文件的修改记录",
        "project": "L2C_FE",
        "expected_matches": ["page.json", "commit"],
    },

    # ---------------------------------------------------------
    # Category 6: CROSS_PROJECT (10 Queries)
    # ---------------------------------------------------------
    {
        "id": "Q090",
        "category": "CROSS_PROJECT",
        "query": "HELLO_FE 前端与 HELLO_BE 后端之间的接口调用契约有哪些？",
        "project": "HELLO_FE",
        "expected_matches": ["order", "api", "trace"],
    },
    {
        "id": "Q091",
        "category": "CROSS_PROJECT",
        "query": "HELLO 后端的销售日报接口在前端有哪些调用点？",
        "project": "HELLO_BE",
        "expected_matches": ["sales", "daily", "report"],
    },
    {
        "id": "Q092",
        "category": "CROSS_PROJECT",
        "query": "L2C monorepo 中 apps/web-ele 依赖了哪些 packages 工作区包？",
        "project": "L2C_FE",
        "expected_matches": ["@core", "packages", "preferences"],
    },
    {
        "id": "Q093",
        "category": "CROSS_PROJECT",
        "query": "packages/@core/base 提供了哪些跨包公共常量？",
        "project": "L2C_FE",
        "expected_matches": ["vben.ts", "constants", "shared"],
    },
    {
        "id": "Q094",
        "category": "CROSS_PROJECT",
        "query": "前后端认证登录接口 /api/auth/login 的端到端调用链是怎样的？",
        "project": "L2C_FE",
        "expected_matches": ["/api/auth/login", "auth.ts", "login"],
    },
    {
        "id": "Q095",
        "category": "CROSS_PROJECT",
        "query": "HELLO_BE 和 HELLO_FE 如何配对协作？",
        "project": "HELLO_FE",
        "expected_matches": ["HELLO_BE", "HELLO_FE", "API"],
    },
    {
        "id": "Q096",
        "category": "CROSS_PROJECT",
        "query": "L2C_FE 是否存在配对的后端工程？",
        "project": "L2C_FE",
        "expected_matches": ["L2C_FE", "backend-mock", "mock"],
    },
    {
        "id": "Q097",
        "category": "CROSS_PROJECT",
        "query": "跨项目共享的 DTO 或实体定义有哪些？",
        "project": "HELLO_BE",
        "expected_matches": ["DTO", "NorthAmericaSalesDailyReportRowDTO"],
    },
    {
        "id": "Q098",
        "category": "CROSS_PROJECT",
        "query": "web-ele 应用是如何从 @core/preferences 获取系统配置的？",
        "project": "L2C_FE",
        "expected_matches": ["preferences.ts", "config.ts", "@core/preferences"],
    },
    {
        "id": "Q099",
        "category": "CROSS_PROJECT",
        "query": "L2C monorepo 中的 pnpm-lock.yaml 锁定了哪些跨包依赖版本？",
        "project": "L2C_FE",
        "expected_matches": ["pnpm-lock.yaml", "package.json"],
    },
    {
        "id": "Q100",
        "category": "CROSS_PROJECT",
        "query": "三个纳管项目 HELLO_FE、HELLO_BE、L2C_FE 的整体架构全貌与角色分工",
        "project": "HELLO_FE",
        "expected_matches": ["HELLO_FE", "HELLO_BE", "L2C_FE"],
    },
]
